service: serverless-webpack-typescript-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          integration: lambda
